---
- name: magento2 site content ownership correct 
  ansible.builtin.file:
    path: /var/www/magento2
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
- name: magento2 site enabled
  notify: restart nginx
  ansible.builtin.file:
    src: /var/www/magento2/nginx.conf
    dest: /etc/nginx/sites-enabled/magento2
    state: link